### ISSUE TITLE
Portal site shows just as blank site

### ISSUE THREAD

**Issue by rwxzig** [marinasundstrom/YourBrand#36]
Hello, I am interested to learn this architecture further, so I have tried to run this project locally and going through the code. After fixing some references, I realized that it is trying to connect to some RabbitMQ service, and after running the RabbitMQ through docker with the following commands:
```ps1
docker run -it --rm --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3.13-management
```
I am able to run the project, but when I go to the portal page, it is just blank.

I modified `Program.cs` in `YourBrand.AppHost` as follows, but it is still blank:

Was:
```cs
var messaging = builder.AddRabbitMQ("messaging", userName: username, password: password, port: 5672)
    .WithHttpEndpoint(port: 15672, targetPort: 15672, name: "management")
    .WithBindMount("../../data/rabbitmq", "/var/lib/rabbitmq");
```
Is now: 
```cs
var messaging = builder.AddRabbitMQ("messaging")
                       .WithDataVolume()
                       .WithManagementPlugin()
                       .PublishAsContainer();
```
And added `aspire-manifest.json` in the same project,
```json
{
    "$schema": "https://json.schemastore.org/aspire-8.0.json",
    "resources": {
        "messaging": {
            "type": "container.v0",
            "connectionString": "rabbitmq://localhost:{messaging-password.value}@{messaging.bindings.tcp.host}:{messaging.bindings.tcp.port}",
            "image": "docker.io/library/rabbitmq:3.13-management",
            "volumes": [
                {
                    "name": "management",
                    "target": "/var/lib/rabbitmq",
                    "readOnly": false
                }
            ],
            "env": {
                "RABBITMQ_DEFAULT_USER": "guest",
                "RABBITMQ_DEFAULT_PASS": "{messaging-password.value}"
            },
            "bindings": {
                "tcp": {
                    "scheme": "tcp",
                    "protocol": "tcp",
                    "transport": "tcp",
                    "targetPort": 5672
                },
                "management": {
                    "scheme": "http",
                    "protocol": "tcp",
                    "transport": "http",
                    "targetPort": 15672
                }
            }
        },
        "messaging-password": {
            "type": "parameter.v0",
            "value": "{messaging-password.inputs.value}",
            "inputs": {
                "value": {
                    "type": "string",
                    "secret": true,
                    "default": {
                        "generate": {
                            "minLength": 22,
                            "special": false
                        }
                    }
                }
            }
        }
    }
}
```
I have seeded the databases, and when I run `IdentityManagement` project alone, I am able to sign in in Duende and see the claims and all that, but when I run through Aspire, it just shows as blank. 

My question is if it is possible to write an initial setup guide, including the setup of the components that it is depended on. And by that I don't mean to include installation or setup, but just perhaps mention that it is running in such port or such address, and expects connection in such and such way.

**Comment by marinasundstrom** [comment]
@rwxzig Thanks for showing interest in my project. You are pointing out something that I should do: Writing instructions.

I initially ran all this in my custom Docker Compose setup with each project running manually. Switched to Aspire a couple of months ago.

I have not tried setting everything upp from scratch. But you should get indications in the Aspire Dashboard. https://localhost:17125/

Or check the browser console.

The Portal is running at: https://localhost:5174/

You need to seed at least the IdentityService and 

AppService for the Portal to run. Then the services you want to run.

I don't know whether "Set up" is needed. I think that is seeded.

"Sync data" simply sends notifications to all services to create Tenants, Users, and Organisations. For when you have recreated and re-seeded service databases.

<img width="265" alt="Screenshot 2024-10-15 at 22 15 25" src="https://github.com/user-attachments/assets/ab05de98-cdb6-4d91-9b63-70f74944b5d7">

I will have to investigate how to run set this project up as a clean slate.

**Comment by marinasundstrom** [comment]
I didn't do a clean install, but I had to reset the Identity Management service and AppService service. So had to re-seed databases and track what I needed, and came up with this this:

# Instructions

1. Run services in Aspire (Requires .NET 9 SDK and Docker):

``dotnet run --project src/YourBrand.AppHost/YourBrand.AppHost.csproj;``

2. Run ``seed.sh`` for seeding initial services databases. This will create default data with test tenant, users, and organisations .

3. Login at ``https://localhost:5040/``, as username ``alice`` (or ``bob``) and password ``Pass123$``. Since the portal will not prompt you to login. (Needs fix)

4. Go to the Portal: https://localhost:5174/ 

5. Activate the desired Portal modules at ``Menu > Administration > Modules``. Click "Populate modules" and "Reload app". (Don't click "Populate" more than once!)

6. Seed the other services as you need.

Activate Portal module “Identity Management” for this:

7. Go ``Menu > Administration > Sync`` to sync and re-sync user data across services. Also used after recreating and seeding service databases.

Keep in mind that modules depend on other modules. ``Sales`` depend on ``Customers``. So activate both.

**Comment by rwxzig** [comment]
Perfect, I will try it again with this instructions and hopefully it will work well. Thanks.

**Comment by marinasundstrom** [comment]
@rwxzig 👍🏻 I'm right now doing a refactoring that will change a lot. But the latest commit should be in a working state, even if tests might not build or so.

**Comment by marinasundstrom** [comment]
@rwxzig I have completed the refactoring now. 580 files where changed. Now using common abstractions. Re-seed is needed.

I haven't tested everything. But if something doesn't work with the apps, that is why.

**Comment by marinasundstrom** [comment]
And with the latest commit I have solved why Portal app didn't load. And you were not able to login from the app.

Probably why it didn't work for you. @rwxzig. I do some loading at start in Portal. Loading modules and organisation data. That needs authentication. And I didn't account for being unauthorized.

There is a decorator component that loads the current org for passing it to the page as a cascading value. I didn't handle the case when that failed due to not being authenticated. 

So I made a quick fix. Now the Portal loads and you can click the Login button. 🙂

**Comment by rwxzig** [comment]
Hello again,
When trying to sign in in the portal, I get this error: `No connection could be made because the target machine actively refused it.`
And I think I have narrowed it down to this two lines:
```
.WithBindMount("../../data/sql-edge", "/var/opt/mssql")
 .WithEnvironment("MSSQL_PID", "Developer")
```
Is there anything specifically on this source `../../data/sql-edge` that you are coping over at the container?

**Comment by marinasundstrom** [comment]
@rwxzig What service is this? Can you connect to the SQL server with Management Studio? Or Azure Data Studio? Dot you see the corresponding database? Have you created and seeded them?

I have had problems with certain SQL Server images in the past. I develop on a Mac.

If you can replace the database image and get it working somehow then you're welcome to try.

With the volume: I'm simply mounting the database to the disk so to not lose state.

**Comment by rwxzig** [comment]
Thanks for your reply. 
It took me the entire day to debug but finally I manage to find the issues: 
1. I had to change the connection string from:
`Server=localhost,1433;User Id=sa;Password=P@ssw0rd;Encrypt=false;`
to:
`Data Source=127.0.0.1,1433;User Id=sa;Password=P@ssw0rd;TrustServerCertificate=True;...`

Note that I had to add `TrustServerCertificate` and remove `Encrypt`.

And also on `Program.cs`
I had to change the sqlServer to:
```cs
var sqlServer = builder.AddSqlServer("sql", password: sqlServerPassword, port: 1433)
    .WithImage("mssql/server")
    .WithImageTag("2022-latest")
    .WithEnvironment("ACCEPT_EULA", "Y")
    .WithEnvironment("MSSQL_DATA_DIR", "/var/opt/mssql/data")
    .WithEnvironment("MSSQL_SA_PASSWORD", sqlServerPassword)
    .WithVolume("yourbrand-sql-data", "/var/opt/mssql")
    .WithEnvironment("MSSQL_PID", "Express")
    .WithLifetime(ContainerLifetime.Persistent);
```
otherwise I was getting that the SQL service was unhealthy and it could not proceed to building the rest of the services.
This is for my curiosity, but in `src/IdentityManagement/seed.sh` you have:
```sh
source ../setup-dev.sh

echo "Seeding Users"
dotnet run --project ./Users/Users.csproj -- --seed --connection-string "$CS;Database=Users"
echo "Done"
```
I guess that `$CS` is connection string, so I replaced that entirely, but is there any other variable on `../setup-dev.sh` that is required?

**Comment by marinasundstrom** [comment]
@rwxzig Don't run the `setup-dev.sh`. That is a file I should remove,

Instead in IdentityManagement: dotnet run -- --seed

Then follow the instructions written earlier:

https://github.com/marinasundstrom/YourBrand/issues/36#issuecomment-2449628035

**Comment by marinasundstrom** [comment]
@rwxzig Do you have the latest version of the repo btw?

I added the instructions here: https://github.com/marinasundstrom/YourBrand/blob/main/Instructions.md

I gathered the seed commands for the core services here:

https://github.com/marinasundstrom/YourBrand/blob/main/seed.sh

You need to start Aspire so the databases are online.

**Comment by rwxzig** [comment]
Yes I followed the instructions and everything is fine. Thanks for your assistance and looking forward to contribute to this project. I saw at least some packages that were referenced more than once that I can clean up. And I can also try to suppress some of the errors that come up on run.
